name: Dev Build & Push

on:
  push:
    branches: ['portal-dashboard']

jobs:
  build-and-test:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-nodejs-build.yml@nodejs
    with:
      node-version: '19.5.0'
      sonar-analysis: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-push:
    needs: [build-and-test]
    uses: eclipse-ecsp/.github/.github/workflows/workflow-nodejs-docker-push.yml@nodejs
    with:
      registry: 'docker.io'
      image-name: 'uidam-portal'
      image-tag: ${{ github.sha }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_API_TOKEN: ${{ secrets.DOCKER_API_TOKEN }}
